# Generated by Django 3.0.4 on 2020-04-21 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_analytics'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Analytics',
            new_name='Activity',
        ),
    ]
